#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <kovan/kovan.h>
#include <sys/time.h>

#include "Constants.h"
#include "claw-utils.h"
#include "drive-utils.h"


#define DRIVE_SPEED_FORWARD -7
#define DRIVE_SPEED_BACKWARD 11

#define SPIN_SPEED 3

void runAutogeneratedCode1() {
    create_drive_straight(0);

    create_spin_CW(150);

    msleep(630);

    create_drive_straight(0);

    create_drive_straight(-500);

    msleep(1320);

    create_drive_straight(0);

    create_spin_CCW(150);

    msleep(1090);

    create_drive_straight(0);

    create_drive_straight(500);

    msleep(1240);

    create_drive_straight(0);

    create_spin_CW(150);

    msleep(280);

    create_drive_straight(0);

    /*create_spin_CW(150);

    msleep(230);

    create_drive_straight(0);*/
    
    create_drive_straight(500);  //back into the slot
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);
    msleep(500);//990

    create_drive_straight(0);

    create_spin_CW(150);

    while (!digital(9)) {
    }

    create_drive_straight(0);
}

void runAutogeneratedCode2() {
    create_drive_straight(0);

    create_drive_straight(-500);

    msleep(1090);

    create_drive_straight(0);
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_DOWN);
    msleep(500);

    create_drive_straight(-500);

    msleep(1341); //time before putting up cube knock

    create_drive_straight(0);
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);
    msleep(500);

    create_drive_straight(-500);

    msleep(971);

    create_drive_straight(0);
}

void jerk() {
    for (int i = 0; i < 20; i++) {
        create_drive_straight(500);
        msleep(500);
        create_drive_straight(-500);
        msleep(500);
    }
    create_drive_straight(0);
}

int main(int argc, char** argv) {

    create_connect();
    raise_claw_to(CLAW_UP_POSITION);
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_DOWN);
    enable_servos();

    runAutogeneratedCode1();
    runAutogeneratedCode2();

    return 0;
}


