#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <kovan/kovan.h>
#include <sys/time.h>
#include <string.h>

#include "song.h"
#include "Constants.h"
#include "claw-utils.h"
#include "drive-utils.h"


#define DRIVE_SPEED_FORWARD -7
#define DRIVE_SPEED_BACKWARD 11

#define SPIN_SPEED 3

void runAutogeneratedCode1() {
    create_drive_straight(0);

    create_spin_CW(150);

    msleep(630);

    create_drive_straight(0);

    create_drive_straight(-500);

    msleep(1320);

    create_drive_straight(0);

    create_spin_CCW(150);

    msleep(1090);

    create_drive_straight(0);

    create_drive_straight(500);

    msleep(1240);

    create_drive_straight(0);

    create_spin_CW(150);

    msleep(280);

    create_drive_straight(0);

    /*create_spin_CW(150);

    msleep(230);

    create_drive_straight(0);*/

    create_drive_straight(500); //back into the slot
    //set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);
    msleep(500); //990
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);
    create_drive_straight(0);

    create_spin_CW(150);

    while (!digital(9)) {
    }
    //set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);
    create_spin_CW(-100);
    msleep(100);  //HOW much to back off from the wall  250 is perfect
    
    create_drive_straight(0);
    //exit(0);
    //create_spin_CW(-100);

    //msleep(250);
}

long getMS(struct timeval time) {
    return time.tv_sec * 1000 + time.tv_usec / 1000;
}

void runAutogeneratedCode2(bool slow) {
    create_drive_straight(0);
    //create_drive_straight(-500);
    //create_drive(-500, -2000);
    create_drive_straight(-500);
    msleep(300);
    msleep(100);
    create_drive(-500, -2000);
    msleep(690);
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_DOWN);
    create_drive_straight(-400);
    msleep(500);
    create_drive(-400, -2000);
    msleep(250);
    create_drive_straight(-400);
    msleep(651); //time before putting up cube knock //Was 1341
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);
     create_drive_straight(-500);
    msleep(1101);
    
    create_drive_straight(0);
}

void jerk() {
    for (int i = 0; i < 20; i++) {
        create_drive_straight(500);
        msleep(500);
        create_drive_straight(-500);
        msleep(500);
    }
    create_drive_straight(0);
}

int main(int argc, char** argv) {
    printf("Create connecting...\n");
    create_connect();
    raise_claw_to(CLAW_UP_POSITION);
    set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);//was down
    enable_servos();
    printf("waiting for input...\n");
    char s[20];
    scanf("%s", s);
    if (strcmp(s, "exit") == 0) {
        return 0;
    }
    playSong();

    //return 0;
    //playCH();
    //return 0;
    //msleep(1000);

    //return 0;1

    //msleep(1000);
    printf("Created connected, GO!!!!!\n");
    
    msleep(1500);

    runAutogeneratedCode2(false);
    return 0;
    runAutogeneratedCode1();
    create_drive_straight(0);
set_servo_position(CUBE_KNOCK_PORT, CUBE_KNOCK_UP);
    printf("waiting for input...\n");
    scanf("%s", s);
    if (strcmp(s, "exit") == 0) {
        return 0;
    } else if (strcmp(s, "slow") == 0) {
        runAutogeneratedCode2(true);
    } else {
        runAutogeneratedCode2(false);
    }
    //char s[20];
    //scanf("%s\n",s);



    return 0;
}


